# Generated by Django 4.0.5 on 2022-07-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(blank=None, max_length=50, null=True)),
                ('user_nickname', models.CharField(blank=None, max_length=50, null=True)),
                ('user_name', models.CharField(blank=None, max_length=50, null=True)),
                ('user_mbti', models.CharField(max_length=50)),
                ('user_keyword1', models.CharField(max_length=50)),
                ('user_keyword2', models.CharField(max_length=50)),
                ('user_keyword3', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_status', models.IntegerField(default=0)),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='가입시간')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
